apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

group = 'expo.modules.stridetts'
version = '1.0.0'

android {
  namespace "expo.modules.stridetts"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}


dependencies {
  implementation "com.google.android.gms:play-services-location:21.3.0"
}
